version: "3.9"

services:
    app:
        image: akirraint/api-automation-demo
        container_name: test-api-server
        ports:
            - "8081:8081"

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui_container
        ports:
            - "8087:8080"
        volumes:
            - ./api/openapi.yaml:/openapi.yaml
        environment:
            SWAGGER_JSON: /openapi.yaml
